title: 一眼离花
url: http://xtruet.github.io
baseurl: '' # 假如你的博客是建在某个目录下的，请在这里加上目录名，并且下面配置的所有链接里的`/public`前也要加，即`/your_baseurl/public`。这一项结尾不要有'/'
author: 霁
paginate: 5
permalink: /posts/:categories/:title # 博文目录

SEO:
- SEOTitle: 霁的博客 | 一眼离花的博客 
- keyword: "BY, BY Blog, XtrueT的博客, 学习, 日常, 借鉴"

head: # 删改前确定知道自己在做什么
- tag: meta # Enable responsiveness on mobile devices
  var:
  - key: name
    value: viewport
  - key: content
    value: width=device-width, initial-scale=1.0, maximum-scale=1
- tag: meta
  var:
  - key: http-equiv
    value: X-UA-Compatible
  - key: content
    value: IE=edge
- tag: meta
  var:
  - key: http-equiv
    value: content-type
  - key: content
    value: 'text/html; charset=utf-8'
- tag: meta # google站点验证
  var:
  - key: name
    value: google-site-verification
  - key: content
    value: 
- tag: meta # baidu站点验证
  var:
  - key: name
    value: baidu-site-verification
  - key: content
    value: 
- tag: meta # yandex站点验证
  var:
  - key: name
    value: yandex-verification
  - key: content
    value: 
- tag: link
  var:
  - key: rel
    value: profile
  - key: href
    value: //gmpg.org/xfn/11
- tag: link # rss
  var:
  - key: rel
    value: alternate
  - key: href
    value: /atom.xml
  - key: title
    value: RSS
  - key: type
    value: application/rss+xml
- tag: link # 网站大图标，我偷懒直接用gravatar了，也可以存在/public里面
  var:
  - key: rel
    value: apple-touch-icon-precomposed
  - key: href
    value: 
- tag: link # 小图标，同上
  var:
  - key: rel
    value: 'shortcut icon'
  - key: href
    value: 
- tag: link # 下面是博客的css，有些插件的css是单独在插件里引用的，假如需要自己的css可以仿照去加在后面。无脑cdn加速了。
  var:
  - key: rel
    value: stylesheet
  - key: href
    value: /public/css/poole.css 
- tag: link
  var:
  - key: rel
    value: stylesheet
  - key: href
    value: /public/css/syntax.css
- tag: link
  var:
  - key: rel
    value: stylesheet
  - key: href
    value: /public/css/lanyon.css
- tag: link
  var:
  - key: rel
    value: stylesheet
  - key: href
    value: /public/css/index.css
- tag: link
  var:
  - key: rel
    value: stylesheet
  - key: href
    value: //cdn.jsdelivr.net/npm/@fortawesome/fontawesome-free/css/all.css # 在https://fontawesome.com/icons 查看支持的图标

body:
  theme-base: theme-base-0e # 可选的值08~0f
  layout-reverse: false # 开启后sidebar在右边，反之左边
  sidebar-overlay: false # 开启后正文不随sidebar移动而移动 #此选项现失效，待修，当前这个选项仅能对sidebar的阴影产生影响

script: # 需要在正文后调用的脚本
- src: //cdn.jsdelivr.net/npm/jquery/dist/jquery.min.js # jQuery
# - src: //cdn.jsdelivr.net/npm/ribbon.js/dist/ribbon.min.js # 彩带背景
- src: //cdn.jsdelivr.net/npm/prismjs/components/prism-core.min.js
- src: //cdn.jsdelivr.net/npm/prismjs/plugins/autoloader/prism-autoloader.min.js
- src: //cdn.jsdelivr.net/npm/prismjs/plugins/line-numbers/prism-line-numbers.min.js
- src: //cdn.jsdelivr.net/npm/prismjs/plugins/toolbar/prism-toolbar.min.js
# - src: //cdn.jsdelivr.net/gh/stevenjoezhang/live2d-widget/autoload.js # live2d
- src: /public/js/prism.js
- src: /public/js/baidu_push.js

# mermaid: # https://github.com/knsv/mermaid
#   enable: true
#   src: //cdn.jsdelivr.net/npm/mermaid/dist/mermaid.min.js
#   stylesheet: //cdn.jsdelivr.net/npm/mermaid/dist/mermaid.min.css
#   markdown_expand: true

PrismJS: # 代码高亮插件，可以在https://prismjs.com/download.html自己定制，我这里只导入了三个自己喜欢的插件。
  enable: true
  src:
    - stylesheet: //cdn.jsdelivr.net/npm/prismjs/themes/prism-okaidia.css # 在https://github.com/PrismJS/prism/tree/master/themes 内查看可用主题，或者也可以搜一些第三方主题
    - stylesheet: //cdn.jsdelivr.net/npm/prismjs/plugins/line-numbers/prism-line-numbers.css
    - stylesheet: //cdn.jsdelivr.net/npm/prismjs/plugins/toolbar/prism-toolbar.css
  plugins:
    line_numbers: true
    autoloader: //cdn.jsdelivr.net/npm/prismjs/components/ # 根据语言自动加载的高亮插件
    toolbar:
      show_language:
        enable: false
        text: 查看语言
        alert: 
      select_code:
        enable: true
        innerHTML: 选中

# katex: # KaTeX
#   enable: true
#   stylesheet: //cdn.jsdelivr.net/npm/katex/dist/katex.min.css
#   src: //cdn.jsdelivr.net/npm/katex/dist/katex.min.js
#   auto-render: //cdn.jsdelivr.net/npm/katex/dist/contrib/auto-render.min.js
#   delimiters: true # 开启行内公式$\KaTeX$支持

sidebar:
  avatar: # 侧边栏显示的头像
    enable: true
    img: /public/image/default.jpg # 头像的地址
    info: #<p></p> # 头像背后的信息
  description: 没有梦想的咸鱼
  social:
#  - title: rss
#    href: /atom.xml
#    class: 'fas fa-rss fa-fw' # rss图标加载不了不知道为什么
  - title: 2640272466@qq.com # email
    href: mailto:2640272466@qq.com
    class: 'fas fa-envelope fa-fw'
  - title: 2640272466 # qq
    class: 'fab fa-qq fa-fw'
  - title: XRF2640272466 # weixin
    class: 'fab fa-weixin fa-fw'
  # - title: zhihu
  #   href: //www.zhihu.com/people/wu.kan/activities
  #   class: 'fab fa-zhihu fa-fw'
  - title: github # email
    href: //github.com/XtrueT
    class: 'fab fa-github fa-fw'
  # - title: WuK # codeforces
  #   href: //codeforces.com/profile/WuK
  #   class: 'far fa-chart-bar fw'
  # - title: WuK # vjudge
  #   href: //vjudge.net/user/WuK
  #   class: 'far fa-smile fa-fw'
  nav:
  - title: '<i class="fas fa-home fa-fw"></i> 首页'
    href: /
  - title: '<i class="fab fa-readme fa-fw"></i> 关于'
    href: /about
  - title: '<i class="fas fa-comments fa-fw"></i> 留言'
    href: /comments
  - title: '<i class="fas fa-tags fa-fw"></i> 标签'
    href: /tags
  - title: '<i class="fas fa-archive fa-fw"></i> 归档'
    href: /archive

simple_jekyll_search:
  enable: true
  src: //cdn.jsdelivr.net/npm/simple-jekyll-search/dest/simple-jekyll-search.min.js
  placeholder: 搜索
  json: /public/simple-jekyll-search/search.json

jekyll_table_of_contents:
  enable: true
  # src: //cdn.jsdelivr.net/gh/ghiculescu/jekyll-table-of-contents/toc.js
  src: /public/js/toc.js

busuanzi:
  enable: true
  src: //cdn.jsdelivr.net/npm/busuanzi/bsz.pure.mini.js
  page_pv: # 页面访问量
    alert: <i class="fas fa-eye fa-fw"></i>
    unit: 次
  site_pv: # 站点访问量
    alert: <i class="fas fa-paw fa-fw"></i>
    unit: 枚
  site_uv: # 访客量
    alert: <i class="fas fa-user-friends fa-fw"></i>
    unit: 人

run_time:
  enable: true
  start_time: '01/08/2019 11:03:56'
  alert: <i class="fas fa-cog fa-spin fa-fw"></i>
  day: 天
  hour: 时
  minute: 分
  second: 秒

copyright:
  enable: true
  text: <a href="//github.com/XtrueT/xtruet.github.com">View on GitHub</a>

post:
  meta:
    enable: true
    date: true
    wordcount:
      enable: true
      unit: 字
    readtime:
      enable: true
      unit: 分
      divided_by: 300
    visitor: # 需要开启valine的visitor选项使之开始计数; 可能会和busuanzi统计的有出入
      enable: true
      unit: 次
    copyright: '<i class="fab fa-creative-commons"></i> <a rel="license" href="//creativecommons.org/licenses/by-sa/4.0/deed.zh">BY-SA 4.0</a>（除特别声明或转载文章外）'
  related:
    enable: true
    title: 相关博文
  reward:
    enable: true
    text: 有帮助，激励一下！
    img: # 万一真的有人打赏呢~
    - id: wechat
      src: /public/image/wechatpay.png
    - id: alipay
      src: /public/image/alipay.png

valine:
  enable: true
  src: //cdn.jsdelivr.net/npm/valine
  appId: SrzzGzdqbBXFOBE3ia8dVAnc-gzGzoHsz
  appKey: 0L9sFb0zNzyK7dRMunmGxbhx
  notify: true # 评论回复邮件提醒
  verify: true # 验证码服务
  avatar: identicon
  placeholder: 在这里评论吧！
  visitor: true # 文章访问量统计
  highlight: true # 代码高亮
  avatarForce: false # 每次访问强制拉取最新的评论列表头像
  recordIP: true # 记录评论者IP

notfound:
  404page:
    enable: true
    src: /public/image/404.jpg
    home: '/'
    description: 回到我的主页
