title: XTRUET
url: http://xtruet.github.io
#baseurl: '' # 假如你的博客是建在某个目录下的，请在这里加上目录名，并且下面配置的所有链接里的`/public`前也要加，即`/your_baseurl/public`。这一项结尾不要有'/'
author: 霁
avatar: https://ss0.bdstatic.com/7Ls0a8Sm1A5BphGlnYG/sys/portrait/item/pp.1.cd298366.xLed3zwhuhnRsSFcnjqzJQ.jpg?1567248569
description: 霁的博客 | 一眼离花的博客 | XtrueT的博客
keyword: "XtrueT的博客,Android,HTML,windows"
paginate: 8
permalink: /posts/:categories/:title # 博文目录


script: # 需要调用的脚本
- src: //cdn.jsdelivr.net/npm/prismjs/components/prism-core.min.js
- src: //cdn.jsdelivr.net/npm/prismjs/plugins/autoloader/prism-autoloader.min.js
- src: //cdn.jsdelivr.net/npm/prismjs/plugins/toolbar/prism-toolbar.min.js
- src: /public/js/prism.js


PrismJS: # 代码高亮插件，可以在https://prismjs.com/download.html自己定制，我这里只导入了三个自己喜欢的插件。
  enable: true
  src:
    - stylesheet: //cdn.jsdelivr.net/npm/prismjs/themes/prism-okaidia.css # 在https://github.com/PrismJS/prism/tree/master/themes 内查看可用主题，或者也可以搜一些第三方主题
    - stylesheet: //cdn.jsdelivr.net/npm/prismjs/plugins/toolbar/prism-toolbar.css
  plugins:
    line_numbers: true
    autoloader: //cdn.jsdelivr.net/npm/prismjs/components/ # 根据语言自动加载的高亮插件
    toolbar:
      show_language:
        enable: false
        text: 查看语言
        alert: 
      select_code:
        enable: true
        innerHTML: 选中


nav:
- title: '首页'
  href: /
- title: '关于'
  href: /README
- title: '留言'
  href: /comments
- title: '标签'
  href: /tags
- title: '归档'
  href: /archive

simple_jekyll_search:
  enable: true
  src: //cdn.jsdelivr.net/npm/simple-jekyll-search/dest/simple-jekyll-search.min.js
  placeholder: 搜索
  json: /public/simple-jekyll-search/search.json

jekyll_table_of_contents:
  enable: true
  # src: //cdn.jsdelivr.net/gh/ghiculescu/jekyll-table-of-contents/toc.js
  src: /public/js/toc.js

post:
  meta:
    enable: true
    date: true
    wordcount:
      enable: true
      unit: 字
    copyright: '<a rel="license" href="//creativecommons.org/licenses/by-sa/4.0/deed.zh">BY-SA 4.0</a>（除特别声明或转载文章外）'
  reward:
    enable: true
    text: 奖励一下
    img: # 万一真的有人打赏呢~
    - id: wechat
      src: /public/image/wechatpay.png
    - id: alipay
      src: /public/image/alipay.png

valine:
  enable: true
  src: //cdn.jsdelivr.net/npm/valine
  appId: SrzzGzdqbBXFOBE3ia8dVAnc-gzGzoHsz
  appKey: 0L9sFb0zNzyK7dRMunmGxbhx
  notify: true # 评论回复邮件提醒
  verify: true # 验证码服务
  avatar: identicon
  placeholder: 在这里评论吧！
  visitor: true # 文章访问量统计
  highlight: true # 代码高亮
  avatarForce: false # 每次访问强制拉取最新的评论列表头像
  recordIP: true # 记录评论者IP

notfound:
  404page:
    enable: true
    src: /public/image/404.jpg
    home: '/'
    description: 回到我的主页
